### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by victorca25** [Krischan74/RTCWHQ#2]
Not an issue, your results look really good and alpha channel is a common problem many attempting to do game upscales face, so this will be mightily useful.

Other upscalers have a subreddit here: https://www.reddit.com/r/GameUpscale/ and share information in a Discord channel here: https://discord.gg/jkFHzGD

I’ll share your GitHub in the Discord channel, but it would be great if you joined us too, so we can share experiences and also add a section for your project there.

**Comment by dclmetatiger** [comment]
I know the channel and I've already joined the channel before, same nick - but I'm not always online in Discord. Do you know who can create a project subchannel there (like the other ones already available)?

**Comment by Anders1980** [comment]
All Hoh! I would like to know where I can download the textures you have processed ? Thank you in advance

**Comment by Anders1980** [comment]
More question. Is it possible to use Your program to process *.dds textures from Call of Duty Classic ?

**Comment by dclmetatiger** [comment]
Texture Upload:
There is no Texture upload because you can convert the textures by yourself with this script. Reason: here in Germany it is still strictly forbidden to upload any images with Swastikas if you're from Germany as you can go to jail for this (this sounds ridiculous but that's the law and they are absolutely serious about that, there are only a few exceptions and a cool game is no exception). And the textures - even the scaled - are still copyrighted material, so no, there won't be any complete HQ PK3 upload from my side. Convert them by yourself or if you don't have a nVidia card: ask somebody with a nVidia card to convert them for you. Sorry.

DDS Textures:
DDS is supported by the Python Image Library (PIL) read-only and my script is written for PNG, TGA and JPG only. So only a few CoD textures are converted at all. At the moment, I don't see any automated solution for this problem in Python as I don't know any DDS writer library there.

So you must extract all textures from the PK3, convert them to - for example - TGA format, then run the RTCWHQ script over them and convert the upscaled textures back to DDS using a 3rd party tool (beware that DDS has different formats, DXT1, DXT5). And you must keep track manually of the file extension so that DDS becomes DDS again. This work won't be any fun at all.

**Comment by Anders1980** [comment]
Thanks for the reply. EDITED: No links to pirated copies, please!

**Comment by victorca25** [comment]
You can just write to us there in the Discord channel and someone will get your subchannel there! If you want to talk directly with someone who can create it, write to alsa and he can help

**Comment by Anders1980** [comment]
Can you create a simple installer of Your script and Python ?

**Comment by dclmetatiger** [comment]
No installer, but I have uploaded two ZIP files to Mediafire containing my Python37 and RTCWHQ folder. Just overwrite your existing Python installation if you only use it for RTCWHQ currently. The RTCWHQ folder can be anywhere, it is only important that python.exe is reachable from there.

[Python37.zip](http://www.mediafire.com/file/il3h07mmpana2bb/Python37.zip/file) 910MB
[RTCWHQ.zip](http://www.mediafire.com/file/368mwaimrej2ae7/RTCWHQ.zip/file) 241MB

**Comment by Anders1980** [comment]
Viel Dank !

**Comment by Anders1980** [comment]
I invite You to the largest Russian forum wolfmap.ru and am asking Your resolution to place there Your exile

**Comment by Anders1980** [comment]
Installed Your program, works fine. Wanted to convert this pack https://www.wolffiles.de/index.php?filebase&fid=4566 there is a bug. Can you tell me why ?

**Comment by dclmetatiger** [comment]
I've just reviewed the problem, the error occurs here at the file "input\textures\castle_props\castle_c30.jpg". Next time provide more details, please - there is a built-in log in my script.

Well, this error can happen sometimes if the input files are already too large or use "wrong" dimensions. First, it makes no sense to resize 1024 pixel textures to 2048 pixels with RTCWHQ as they are already "hires enough". The problem here is that CUDA is simply running out of memory. Either you must use a graphics card with more GPU memory than 8GB or resize the texture causing errors manually before running RTCWHQ. Just a notice: my script is written for the original RTCW and ET, not custom packs. They may work or not.

The pack you've linked is a custom pack. If the creators don't respect the power of two texture sizes, anything can happen (the graphics card can resize such textures when they're loaded in the game but they should be in 2^n pixel dimensions only to prevent blurry results). In this case, the texture is 1024x764 pixels which is NOT 2^n. RTCWHQ tries to resize it to 1024x512 pixels and again to 4096x2048 which is too much for the GPU RAM (Limit at 8GB is approx. 1024x512 ~ 512.000 pixels  but this value can vary and depends on the currently available GPU RAM).

In general, RTCWHQ already can handle such wrong texture sizes but in this case something went wrong. I must investigate this further to find a solution (if there is any), a quick fix to resize the texture causing the error is to resize it to for example 1024x1024 or 512x512 or 1024x512 pixels (which is 2^n compliant).

**Comment by Anders1980** [comment]
Textures from archive https://www.wolffiles.de/index.php?filebase&fid=4566 I adjust the size of the original and will soon run through the scripts

**Comment by Anders1980** [comment]
https://yadi.sk/d/pjdHqRTmW-ctVQ First version , temporary download

**Comment by Anders1980** [comment]
Dear author. The error was discovered. Textures are transformed into progressive JPEG and when you try to start the game with them catch the flight. Is it possible to change the transformation in baseline JPEG ?

**Comment by Anders1980** [comment]
Requested feature was omitted at compile time   -  error text

**Comment by Anders1980** [comment]
https://yadi.sk/d/pjdHqRTmW-ctVQ I received a pack of textures easily runs on ioRtCW without errors. It is possible that ioRtCW as a newer engine, supports all kinds of format JPG and PNG

**Comment by Anders1980** [comment]
Your program can use other models from ESRGAN ?

**Comment by Anders1980** [comment]
https://www.moddb.com/games/return-to-castle-wolfenstein/addons/sp-pak2 Pack of graphic differences from the German version of the game

**Comment by dclmetatiger** [comment]
Please don't get me wrong, but this board is here to post problems with or general comments on RTCWHQ and not to link to other texture packs - there are enough other forums for that. And if RTCWHQ can handle other models you have to try it yourself, at least all models I found on the internet until May 2019 worked. I'm closing this topic now.
